version: "3.9"
services:
  shortcode:
    container_name: shortcodes
    restart: always
    build: .
    ports:
      - "8082:8082"
    volumes:
      - /var/aes:/aes
      - /var/logs:/logs
networks:
  spring-cloud-network:
    driver: shortcodes