version: "3.9"
services:
  shortcode:
    build: .
    image: shortcodes:v1
    container_name: shortcodes
    network_mode: host
    restart: always
    #ports:
    #  - "8082:8082"
    volumes:
      - /var/aes:/aes
      - /var/logs:/logs
#networks:
#  spring-cloud-network:
#    driver: shortcodes