spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=devops
spring.datasource.password=devops
spring.datasource.url=jdbc:postgresql://10.10.2.9:5432/short_codes?createDatabaseIfNotExist=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl=true

service.params.smtphost=172.16.2.60
service.params.finquery.host=10.10.2.8:8081

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

keycloak.realm=ShortCodeApp
keycloak.auth-server-url=https://keycloakv2.abcthebank.com:8099
keycloak.resource=short-code-api
keycloak.public-client=true
keycloak.bearer-only=true
keycloak.ssl-required=external
keycloak.cors=true

keycloak.config.token-url=https://keycloakv2.abcthebank.com:8099/realms/ShortCodeApp/protocol/openid-connect/token
keycloak.config.client-id=short-code-api
keycloak.config.grant-type=password