server.port=8082

spring.profiles.active=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=short_codes_user
spring.datasource.password=5Hort_codes
spring.datasource.url=jdbc:postgresql://172.14.0.136:5432/short_codes?createDatabaseIfNotExist=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl=true

service.params.smtphost=172.16.2.60

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

keycloak.config.token-url=https://keycloakuat.abcthebank.com:8099/realms/KRAITAXREALM/protocol/openid-connect/token